import SwiftUI
import AppKit

extension Image {
    /// Loads a PNG bundled as a plain SwiftPM resource copy (see
    /// `Package.swift`'s `.copy("Resources")`).
    ///
    /// `Bundle.module` is auto-generated by SwiftPM for targets with resources,
    /// but is unavailable when building via an Xcode project (.xcodeproj).
    /// The conditional below selects the right bundle for each build system.
    static func bundled(_ name: String, fallbackSystemImage: String) -> Image {
        #if SWIFT_PACKAGE
        let bundle = Bundle.module
        #else
        let bundle = Bundle.main
        #endif
        guard
            let url = bundle.url(forResource: name, withExtension: "png", subdirectory: "Resources"),
            let nsImage = NSImage(contentsOf: url)
        else {
            return Image(systemName: fallbackSystemImage)
        }
        return Image(nsImage: nsImage)
    }
}
